services:
  crawler-service:
    build:
      context: .
      target: development
    ports:
      - "3500:3500"
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: