services:
  crawler-analyst-investment-service:
    build: .
    ports:
      - "3500:3500"
    environment:
#      - BRAPI_TOKEN=${BRAPI_TOKEN:-}
      - BACEN_BASE_URL=https://api.bcb.gov.br/dados/serie/bcdata.sgs
      - BRAPI_BASE_URL=https://brapi.dev/api
      - CVM_BASE_URL=https://dados.cvm.gov.br/dados
      - IBGE_BASE_URL=https://servicodados.ibge.gov.br/api/v3
    volumes:
      - .:/app  # hot reload em desenvolvimento
    command: uvicorn main:app --host 0.0.0.0 --port 3500 --reload
